apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tram-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ITKIMJUNHEE/2026-tram.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: tram
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
